### ISSUE TITLE
Cannot find code for and unable to load some data from the porous graphene dataset

### ISSUE THREAD

**Issue by jkotrc** [millskyle/extensive_deep_neural_networks#2]
The research article "Extensive deep neural networks for transferring small scale learning to large scale systems" links this GitHub repository for code that uses the "Porous Graphene" dataset.

There is an issue with the dataset, that is, I am unable to extract the 'energy' or 'file_source' label:
```
$ python sample_explore.py
KEYS <KeysViewHDF5 ['cell', 'coordinates', 'energy', 'file_source']>
CLASS: cell
DIMENSIONS: (3, 3)
DATA: <HDF5 dataset "cell": shape (3, 3), type "<f8">
CLASS: coordinates
DIMENSIONS: (390, 4)
DATA: <HDF5 dataset "coordinates": shape (390, 4), type "<f8">
CLASS: energy
DIMENSIONS: ()
DATA: <HDF5 dataset "energy": shape (), type "<f8">
CLASS: file_source
DIMENSIONS: ()
DATA: <HDF5 dataset "file_source": shape (), type "|O">
```
I'm assuming 'file_source' should point to something like `/archive/01/kmills/ednn_for_paper/training_data/holey_sheets/unprocessed/vasprun/train/904efc8c-63ed-4644-8abc-ec5c4a470359/vasprun.xml`, but this file is absent from the archive

https://nrc-digital-repository.canada.ca/eng/view/object/?id=9f09901d-0736-4204-a35d-0c88ffb8da3b

**Comment by millskyle** [comment]
That path is just a note about where the specific entry came from. It is not intended to be included in the archive. I am unsure what you mean about not being able to access the energy.  Your output seems to indicate that the file indeed contains an "energy" dataset.

**Comment by jkotrc** [comment]
Ah got it, my bad! It was just me who couldn't figure out how to extract values from empty datasets, whoops
